FROM elixir:1.5.3
ENV DEBIAN_FRONTEND=noninteractive

EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash

WORKDIR /app

COPY ./todo_with_auth.tar.gz ./

RUN tar xfz todo_with_auth.tar.gz
RUN mix deps.compile
ENTRYPOINT ["bin/todo_with_auth"]